### ISSUE TITLE
"SikuliX version 2.1.x " still in docs

### ISSUE THREAD

**Issue by gshields** [SikuliX/sikulix.github.io#1]
Sad to see the reset back to 2.0 version, was starting to use the recorder in that version.
Also I enjoyed the old documentation better that the new version. since they flowed better and had more information.
I would have rather seen the repository cloned from 2.05 to sikuli+ and have the old sikulix 2.1 system left

**Comment by RaiMan** [comment]
> "SikuliX version 2.1.x " still in docs

Not really sure what you mean by that.

Current status:
- I did not touch the branch master (which is 2.1.0 alpha) since months (in fact it is not useable in its current state, why I stopped the snapshot builds)
- I concentrated on the release of 2.0.5
- the recorder and sever of 2.1.0 will get its way into the 2.0.6 (there will soon be snapshot builds available again) 
- the stuff is in branch release_2.0.x

I started to work on a new website, that will integrate the docs and a blog here.
The current docs will remain "forever" but will no longer be updated. 
We are currently active, to migrate the content and give it a better structure and handy features.

Hope you can live with that ;-)
